// src/routes/Home.tsx
import React, { useEffect, useMemo, useState } from 'react';
import { useLiveQuery } from 'dexie-react-hooks';
import { Link } from 'react-router-dom';
import { db, type BodyMetric, type Food, type Goal, type UserSettings } from '../lib/db';
import { generateId } from '../lib';
import { supabase } from '../lib/supabaseClient';

type SettingsRow = UserSettings & { id: 'local-settings' };

const SETTINGS_ID: SettingsRow['id'] = 'local-settings';

function toYyyyMmDd(date: Date) {
  return date.toISOString().split('T')[0];
}

function getWeekStart(date: Date) {
  const start = new Date(date);
  const day = start.getDay();
  const diffToMonday = day === 0 ? 6 : day - 1;
  start.setDate(start.getDate() - diffToMonday);
  start.setHours(0, 0, 0, 0);
  return start;
}

function getWorkoutDurationMinutes(startTime: string, endTime?: string) {
  if (!endTime) return 0;
  const start = new Date(startTime).getTime();
  const end = new Date(endTime).getTime();
  if (!Number.isFinite(start) || !Number.isFinite(end) || end <= start) return 0;
  return Math.round((end - start) / 60000);
}

function goalsStorageKey(date: string) {
  return `home-goals-tracking:${date}`;
}

function summaryStorageKey(date: string) {
  return `home-day-summary:${date}`;
}

export default function Home() {
  const now = new Date();
  const today = useMemo(() => toYyyyMmDd(now), [now]);
  const weekStartIso = useMemo(() => getWeekStart(now).toISOString(), [now]);
  const [currentUserId, setCurrentUserId] = useState<string>('local-user');
  const [trackedGoals, setTrackedGoals] = useState<Record<string, boolean>>({});
  const [daySummary, setDaySummary] = useState('');
  const [weightForm, setWeightForm] = useState({
    date: today,
    value: '',
    unit: 'kg'
  });

  const recentWeight = useLiveQuery(
    async () => {
      const list = await db.metrics
        .where('type')
        .equals('weight')
        .and((row) => row.user_id === currentUserId)
        .toArray();

      return list
        .sort((a, b) => {
          if (a.date === b.date) return (b.created_at?.getTime() ?? 0) - (a.created_at?.getTime() ?? 0);
          return a.date < b.date ? 1 : -1;
        })
        .slice(0, 7);
    },
    [currentUserId],
    [] as BodyMetric[]
  );

  const data = useLiveQuery(async () => {
    const [todayLogs, settings, workouts, goal] = await Promise.all([
      db.logs.where('date').equals(today).toArray(),
      db.settings.get(SETTINGS_ID as string) as Promise<SettingsRow | undefined>,
      db.workouts.toArray(),
      db.goals.where('start_date').belowOrEqual(today).reverse().first() as Promise<Goal | undefined>
    ]);

    const foodIds = [...new Set(todayLogs.map((log) => log.food_id))];
    const foods = foodIds.length ? await db.foods.where('id').anyOf(foodIds).toArray() : [];
    const foodsMap = foods.reduce<Record<string, Food>>((acc, food) => {
      acc[food.id] = food;
      return acc;
    }, {});

    const calorieTotals = todayLogs.reduce(
      (acc, log) => {
        const food = foodsMap[log.food_id];
        if (!food) return acc;
        const amount = Number(log.amount_consumed) || 0;
        acc.calories += food.calories * amount;
        acc.protein += food.protein * amount;
        acc.carbs += food.carbs * amount;
        acc.fat += food.fat * amount;
        return acc;
      },
      { calories: 0, protein: 0, carbs: 0, fat: 0 }
    );

    const thisWeekWorkouts = workouts.filter((workout) => workout.start_time >= weekStartIso);
    const thisWeekMinutes = thisWeekWorkouts.reduce(
      (sum, workout) => sum + getWorkoutDurationMinutes(workout.start_time, workout.end_time),
      0
    );
    const todayWorkoutCount = workouts.filter((workout) => workout.start_time.startsWith(today)).length;

    return {
      settings,
      goal,
      todayLogsCount: todayLogs.length,
      calorieTotals,
      workoutsCount: workouts.length,
      todayWorkoutCount,
      thisWeekWorkoutsCount: thisWeekWorkouts.length,
      thisWeekMinutes
    };
  }, [today, weekStartIso]);

  const calorieGoal = data?.goal?.calories_target ?? data?.settings?.nutrition?.calorieBudget ?? 2000;
  const proteinGoal =
    data?.goal?.protein_target ??
    Math.round((calorieGoal * ((data?.settings?.nutrition?.proteinPercent ?? 30) / 100)) / 4);
  const carbsGoal =
    data?.goal?.carbs_target ??
    Math.round((calorieGoal * ((data?.settings?.nutrition?.carbPercent ?? 40) / 100)) / 4);
  const fatGoal =
    data?.goal?.fat_target ??
    Math.round((calorieGoal * ((data?.settings?.nutrition?.fatPercent ?? 30) / 100)) / 9);

  const caloriesConsumed = Math.round(data?.calorieTotals.calories ?? 0);
  const proteinConsumed = Math.round(data?.calorieTotals.protein ?? 0);
  const carbsConsumed = Math.round(data?.calorieTotals.carbs ?? 0);
  const fatConsumed = Math.round(data?.calorieTotals.fat ?? 0);
  const calorieProgress = Math.min((caloriesConsumed / Math.max(1, calorieGoal)) * 100, 100);
  const proteinProgress = Math.min((proteinConsumed / Math.max(1, proteinGoal)) * 100, 100);
  const carbsProgress = Math.min((carbsConsumed / Math.max(1, carbsGoal)) * 100, 100);
  const fatProgress = Math.min((fatConsumed / Math.max(1, fatGoal)) * 100, 100);
  const trackableGoals = useMemo(() => {
    const goals = [{ id: 'carbs', label: 'Carbs', detail: `${carbsConsumed} / ${carbsGoal} g` }];

    if ((data?.goal?.sleep_target ?? 0) > 0) {
      goals.push({ id: 'sleep', label: 'Sleep', detail: `Target: ${data?.goal?.sleep_target} hrs` });
    }
    if ((data?.goal?.water_target ?? 0) > 0) {
      goals.push({ id: 'water', label: 'Water', detail: `Target: ${data?.goal?.water_target} ml` });
    }
    if ((data?.goal?.weight_target ?? 0) > 0) {
      goals.push({ id: 'weight', label: 'Weight', detail: `Target: ${data?.goal?.weight_target}` });
    }
    return goals;
  }, [
    carbsConsumed,
    carbsGoal,
    data?.goal?.sleep_target,
    data?.goal?.water_target,
    data?.goal?.weight_target
  ]);

  const completedTrackedCount = trackableGoals.filter((goal) => trackedGoals[goal.id]).length;

  useEffect(() => {
    supabase.auth.getSession().then(({ data: { session } }) => {
      setCurrentUserId(session?.user?.id ?? 'local-user');
    });

    const {
      data: { subscription }
    } = supabase.auth.onAuthStateChange((_event, session) => {
      setCurrentUserId(session?.user?.id ?? 'local-user');
    });

    return () => subscription.unsubscribe();
  }, []);

  useEffect(() => {
    if (typeof window === 'undefined') return;

    try {
      const storedGoals = window.localStorage.getItem(goalsStorageKey(today));
      setTrackedGoals(storedGoals ? JSON.parse(storedGoals) : {});
    } catch {
      setTrackedGoals({});
    }

    const storedSummary = window.localStorage.getItem(summaryStorageKey(today));
    setDaySummary(storedSummary ?? '');
  }, [today]);

  useEffect(() => {
    if (typeof window === 'undefined') return;
    window.localStorage.setItem(goalsStorageKey(today), JSON.stringify(trackedGoals));
  }, [today, trackedGoals]);

  useEffect(() => {
    if (typeof window === 'undefined') return;
    window.localStorage.setItem(summaryStorageKey(today), daySummary);
  }, [today, daySummary]);

  const handleGoalToggle = (goalId: string) => {
    setTrackedGoals((prev) => ({ ...prev, [goalId]: !prev[goalId] }));
  };

  const addWeight = async (event: React.FormEvent) => {
    event.preventDefault();
    const value = Number(weightForm.value);

    if (!Number.isFinite(value) || value <= 0) {
      alert('Enter a valid weight');
      return;
    }

    try {
      const metric: BodyMetric = {
        id: generateId(),
        user_id: currentUserId,
        date: weightForm.date || today,
        type: 'weight',
        value: Math.round(value * 10) / 10,
        unit: weightForm.unit,
        synced: 0,
        created_at: new Date()
      };

      await db.metrics.put(metric);
      setWeightForm((prev) => ({ ...prev, value: '' }));
    } catch (error) {
      console.error(error);
      alert('Failed to add weight');
    }
  };

  return (
    <div className="min-h-screen bg-page pb-24 font-sans">
      <header className="bg-card shadow-sm sticky top-0 z-10 border-b border-border-subtle">
        <div className="max-w-md mx-auto px-4 py-3">
          <h1 className="text-2xl font-extrabold text-text-main">Dashboard</h1>
          <p className="text-xs text-text-muted mt-0.5">Today&apos;s overview across calories, workouts, and goals</p>
        </div>
      </header>

      <main className="max-w-md mx-auto p-4 space-y-4">
        <Link
          to="/log"
          className="block bg-card rounded-2xl p-6 border border-border-subtle shadow-sm hover:border-brand-light transition-all active:scale-[0.99]"
        >
          <p className="mt-2 text-3xl font-extrabold text-text-main">
            {caloriesConsumed} of {Math.round(calorieGoal)}{' '}
            <span className="text-sm font-semibold text-text-muted align-middle">Calories Eaten</span>
            <span className="ml-2 text-xs font-bold text-brand bg-surface px-2.5 py-1 rounded-full align-middle">
              {data?.todayLogsCount ?? 0} logs
            </span>
          </p>

          <div className="mt-3 h-4 bg-surface rounded-full overflow-hidden shadow-inner">
            <div
              className="h-full bg-blue-500 dark:bg-blue-600 rounded-full transition-all duration-700 ease-out shadow-sm"
              style={{ width: `${calorieProgress}%` }}
            />
          </div>

          <div className="grid grid-cols-3 gap-6 mt-6">
            <div className="text-center">
              <p className="text-xs text-text-muted mb-2 font-medium">Protein</p>
              <div className="relative h-2 bg-surface rounded-full mb-2">
                <div
                  className="absolute top-0 left-0 h-full bg-macro-protein rounded-full transition-all duration-500"
                  style={{ width: `${proteinProgress}%` }}
                />
              </div>
              <p className="text-xs font-bold text-text-main">{proteinConsumed} <span className="text-text-muted font-normal">/ {proteinGoal}g</span></p>
            </div>

            <div className="text-center">
              <p className="text-xs text-text-muted mb-2 font-medium">Carbs</p>
              <div className="relative h-2 bg-surface rounded-full mb-2">
                <div
                  className="absolute top-0 left-0 h-full bg-macro-carbs rounded-full transition-all duration-500"
                  style={{ width: `${carbsProgress}%` }}
                />
              </div>
              <p className="text-xs font-bold text-text-main">{carbsConsumed} <span className="text-text-muted font-normal">/ {carbsGoal}g</span></p>
            </div>

            <div className="text-center">
              <p className="text-xs text-text-muted mb-2 font-medium">Fat</p>
              <div className="relative h-2 bg-surface rounded-full mb-2">
                <div
                  className="absolute top-0 left-0 h-full bg-macro-fat rounded-full transition-all duration-500"
                  style={{ width: `${fatProgress}%` }}
                />
              </div>
              <p className="text-xs font-bold text-text-main">{fatConsumed} <span className="text-text-muted font-normal">/ {fatGoal}g</span></p>
            </div>
          </div>
        </Link>

        <Link
          to="/workouts"
          className="block bg-card rounded-2xl p-5 border border-border-subtle shadow-sm hover:border-brand-light transition-all active:scale-[0.99]"
        >
          <p className="text-sm font-bold uppercase tracking-wide text-text-muted">Workout</p>
          <div className="mt-3 grid grid-cols-3 gap-3">
            <div className="bg-surface rounded-xl p-2.5 text-center">
              <p className="text-2xl font-extrabold text-text-main">{data?.todayWorkoutCount ?? 0}</p>
              <p className="text-[11px] text-text-muted">Today</p>
            </div>
            <div className="bg-surface rounded-xl p-2.5 text-center">
              <p className="text-2xl font-extrabold text-text-main">{data?.thisWeekWorkoutsCount ?? 0}</p>
              <p className="text-[11px] text-text-muted">This week</p>
            </div>
            <div className="bg-surface rounded-xl p-2.5 text-center">
              <p className="text-2xl font-extrabold text-text-main">{data?.thisWeekMinutes ?? 0}</p>
              <p className="text-[11px] text-text-muted">Week mins</p>
            </div>
          </div>
          <p className="mt-3 text-xs font-medium text-text-muted">Total workouts logged: {data?.workoutsCount ?? 0}</p>
        </Link>

        <section className="bg-card rounded-2xl p-5 border border-border-subtle shadow-sm">
          <div className="flex items-center justify-between gap-3">
            <p className="text-sm font-bold uppercase tracking-wide text-text-muted">Weight log</p>
            <Link to="/profile" className="text-xs font-medium text-text-muted hover:text-text-main">
              Profile
            </Link>
          </div>

          <form onSubmit={addWeight} className="grid grid-cols-3 gap-2 mt-3 mb-3">
            <input
              type="date"
              value={weightForm.date}
              onChange={(e) => setWeightForm((prev) => ({ ...prev, date: e.target.value }))}
              className="col-span-2 p-2.5 rounded-xl border border-border-subtle bg-surface text-text-main text-sm"
            />
            <select
              value={weightForm.unit}
              onChange={(e) => setWeightForm((prev) => ({ ...prev, unit: e.target.value }))}
              className="col-span-1 p-2.5 rounded-xl border border-border-subtle bg-surface text-text-main text-sm"
            >
              <option value="kg">kg</option>
              <option value="lb">lb</option>
            </select>
            <input
              type="number"
              step="0.1"
              min="0"
              value={weightForm.value}
              onChange={(e) => setWeightForm((prev) => ({ ...prev, value: e.target.value }))}
              placeholder="Weight"
              className="col-span-2 p-2.5 rounded-xl border border-border-subtle bg-surface text-text-main text-sm"
            />
            <button
              type="submit"
              className="col-span-1 py-2.5 rounded-xl bg-brand text-brand-fg font-bold text-xs hover:opacity-90 transition-opacity"
            >
              Add
            </button>
          </form>

          <div className="space-y-2">
            {recentWeight.length === 0 ? (
              <p className="text-xs text-text-muted">No recent weight entries.</p>
            ) : (
              recentWeight.map((entry) => (
                <div key={entry.id} className="bg-surface rounded-lg px-3 py-2 flex items-center justify-between">
                  <p className="text-xs text-text-muted">{entry.date}</p>
                  <p className="text-sm font-semibold text-text-main">
                    {entry.value} {entry.unit}
                  </p>
                </div>
              ))
            )}
          </div>
        </section>

        <section className="bg-card rounded-2xl p-5 border border-border-subtle shadow-sm">
          <div className="flex items-center justify-between gap-3">
            <p className="text-sm font-bold uppercase tracking-wide text-text-muted">Track goals</p>
            <p className="text-xs font-bold text-text-main bg-surface px-2.5 py-1 rounded-full">
              {completedTrackedCount}/{trackableGoals.length} done
            </p>
          </div>

          <div className="mt-3 space-y-2">
            {trackableGoals.map((goal) => (
              <label
                key={goal.id}
                className="flex items-center justify-between gap-3 bg-surface px-3 py-2 rounded-lg cursor-pointer"
              >
                <div className="min-w-0">
                  <p className="text-sm font-semibold text-text-main">{goal.label}</p>
                  <p className="text-xs text-text-muted truncate">{goal.detail}</p>
                </div>
                <input
                  type="checkbox"
                  checked={Boolean(trackedGoals[goal.id])}
                  onChange={() => handleGoalToggle(goal.id)}
                  className="h-4 w-4 accent-brand"
                />
              </label>
            ))}
          </div>

          <div className="mt-4">
            <label htmlFor="day-summary" className="block text-xs font-bold uppercase tracking-wide text-text-muted mb-2">
              Day summary
            </label>
            <input
              id="day-summary"
              type="text"
              value={daySummary}
              onChange={(event) => setDaySummary(event.target.value)}
              placeholder="How did today go?"
              className="w-full rounded-lg border border-border-subtle bg-surface px-3 py-2 text-sm text-text-main placeholder:text-text-muted focus:outline-none focus:ring-2 focus:ring-brand/30"
            />
          </div>

          <Link to="/profile" className="mt-3 inline-block text-xs font-medium text-text-muted hover:text-text-main">
            Manage goals and reminders
          </Link>
        </section>
      </main>
    </div>
  );
}

// src/routes/Home.svelte
<script lang="ts">
	import { db, type DailyLog, type Food } from '$lib/db';
	import { liveQueryStore } from '$lib/stores/liveQuery';
	import { Plus, Utensils, ChevronLeft, ChevronRight, Calendar } from 'lucide-svelte';

	// State for Date Navigation
	let currentDate = new Date();
	
	function changeDate(days: number) {
		const newDate = new Date(currentDate);
		newDate.setDate(currentDate.getDate() + days);
		currentDate = newDate;
	}

	function getYyyyMmDd(date: Date) {
		const yyyy = date.getFullYear();
		const mm = String(date.getMonth() + 1).padStart(2, '0');
		const dd = String(date.getDate()).padStart(2, '0');
		return `${yyyy}-${mm}-${dd}`;
	}

	$: formattedDate = getYyyyMmDd(currentDate);
	$: displayDate = currentDate.toLocaleDateString(undefined, { weekday: 'long', month: 'short', day: 'numeric' });
	$: isToday = formattedDate === getYyyyMmDd(new Date());

	// Reactive Store for Data - updates when formattedDate changes
	$: data = liveQueryStore(async () => {
		// 1. Fetch Logs for selected date
		const logs = await db.logs.where('date').equals(formattedDate).toArray();

		// 2. Fetch Associated Foods
		const foodIds = logs.map((l) => l.food_id);
		// bulkGet returns (T | undefined)[] in same order as keys
		const foods = await db.foods.bulkGet(foodIds);

		// Join Logs with Foods
		const logsWithFood = logs.map((log, i) => {
			const food = foods[i];
			if (!food) return null;
			return {
				...log,
				food
			};
		}).filter((item): item is DailyLog & { food: Food } => item !== null);

		// 3. Fetch Goal (latest active goal relative to selected date)
		const goal = await db.goals
			.where('start_date')
			.belowOrEqual(formattedDate)
			.reverse()
			.first();

		return {
			logs: logsWithFood,
			goal
		};
	});

	// Derived Calculations
	$: logs = $data?.logs ?? [];
	$: goal = $data?.goal;

	$: totalCalories = logs.reduce((sum, item) => sum + (item.food.calories * item.amount_consumed), 0);
	$: totalProtein = logs.reduce((sum, item) => sum + (item.food.protein * item.amount_consumed), 0);
	$: totalCarbs = logs.reduce((sum, item) => sum + (item.food.carbs * item.amount_consumed), 0);
	$: totalFat = logs.reduce((sum, item) => sum + (item.food.fat * item.amount_consumed), 0);

	// Goal Targets (Defaults just in case)
	$: goalCalories = goal?.calories_target || 2000;
	$: goalProtein = goal?.protein_target || 150;
	$: goalCarbs = goal?.carbs_target || 200;
	$: goalFat = goal?.fat_target || 60;

	// Progress Percentages
	$: pctCalories = Math.min((totalCalories / goalCalories) * 100, 100);
	$: pctProtein = Math.min((totalProtein / goalProtein) * 100, 100);
	$: pctCarbs = Math.min((totalCarbs / goalCarbs) * 100, 100);
	$: pctFat = Math.min((totalFat / goalFat) * 100, 100);
</script>

<div class="min-h-screen bg-page pb-20 font-sans">
	<!-- Header -->
	<header class="bg-card shadow-sm sticky top-0 z-10 border-b border-border-subtle">
		<div class="max-w-md mx-auto px-4 py-3 flex justify-between items-center">
			<h1 class="text-xl font-bold text-text-main hidden sm:block">Dashboard</h1>
			
			<div class="flex items-center justify-between w-full sm:w-auto bg-surface rounded-full px-1 py-1 border border-border-subtle shadow-sm mx-auto sm:mx-0">
				<button 
					class="p-2 hover:bg-card rounded-full transition-colors text-text-muted hover:text-text-main"
					on:click={() => changeDate(-1)}
					aria-label="Previous day"
				>
					<ChevronLeft size={18} />
				</button>
				
				<button 
					class="flex flex-col items-center px-4 cursor-pointer hover:bg-card/50 rounded-lg transition-colors py-1" 
					on:click={() => { currentDate = new Date(); }}
					title="Jump to Today"
				>
					<span class="text-sm font-bold text-text-main leading-none flex items-center gap-1.5">
						<Calendar size={12} class="text-brand" />
						{isToday ? 'Today' : displayDate}
					</span>
					{#if !isToday}
						<span class="text-[10px] text-text-muted leading-none mt-0.5">{displayDate}</span>
					{/if}
				</button>

				<button 
					class="p-2 hover:bg-card rounded-full transition-colors text-text-muted hover:text-text-main"
					on:click={() => changeDate(1)}
					aria-label="Next day"
				>
					<ChevronRight size={18} />
				</button>
			</div>
		</div>
	</header>

	<main class="max-w-md mx-auto p-4 space-y-6">
		<!-- Progress Overview Card -->
		<div class="bg-card rounded-2xl shadow-sm p-6 border border-border-subtle">
			<div class="flex justify-between items-end mb-2">
				<div>
					<p class="text-sm text-text-muted font-medium uppercase tracking-wide">Calories</p>
					<div class="flex items-baseline gap-1 mt-1">
						<span class="text-4xl font-extrabold text-text-main">{Math.round(totalCalories)}</span>
						<span class="text-sm text-text-muted font-medium">/ {goalCalories}</span>
					</div>
				</div>
				<div class="text-right mb-1">
					<p class="text-xs font-bold text-emerald-700 bg-emerald-100 dark:bg-emerald-900/30 dark:text-emerald-400 px-3 py-1 rounded-full inline-block">
						{Math.round(goalCalories - totalCalories)} LEFT
					</p>
				</div>
			</div>

			<!-- Calorie Progress Bar -->
			<div class="h-4 bg-surface rounded-full overflow-hidden mb-8 shadow-inner">
				<div 
					class="h-full bg-blue-500 dark:bg-blue-600 rounded-full transition-all duration-700 ease-out shadow-sm"
					style="width: {pctCalories}%"
				></div>
			</div>

			<!-- Macros Grid -->
			<div class="grid grid-cols-3 gap-6">
				<!-- Protein -->
				<div class="text-center">
					<p class="text-xs text-text-muted mb-2 font-medium">Protein</p>
					<div class="relative h-2 bg-surface rounded-full mb-2">
						<div class="absolute top-0 left-0 h-full bg-macro-protein rounded-full transition-all duration-500" style="width: {pctProtein}%"></div>
					</div>
					<p class="text-xs font-bold text-text-main">{Math.round(totalProtein)} <span class="text-text-muted font-normal">/ {goalProtein}g</span></p>
				</div>
				<!-- Carbs -->
				<div class="text-center">
					<p class="text-xs text-text-muted mb-2 font-medium">Carbs</p>
					<div class="relative h-2 bg-surface rounded-full mb-2">
						<div class="absolute top-0 left-0 h-full bg-macro-carbs rounded-full transition-all duration-500" style="width: {pctCarbs}%"></div>
					</div>
					<p class="text-xs font-bold text-text-main">{Math.round(totalCarbs)} <span class="text-text-muted font-normal">/ {goalCarbs}g</span></p>
				</div>
				<!-- Fat -->
				<div class="text-center">
					<p class="text-xs text-text-muted mb-2 font-medium">Fat</p>
					<div class="relative h-2 bg-surface rounded-full mb-2">
						<div class="absolute top-0 left-0 h-full bg-macro-fat rounded-full transition-all duration-500" style="width: {pctFat}%"></div>
					</div>
					<p class="text-xs font-bold text-text-main">{Math.round(totalFat)} <span class="text-text-muted font-normal">/ {goalFat}g</span></p>
				</div>
			</div>
		</div>

		<!-- Recent Logs -->
		<div>
			<h2 class="text-lg font-bold text-text-main mb-4 px-1">{isToday ? "Today's Meals" : "Meals"}</h2>
			
			{#if !$data}
				<div class="flex justify-center p-12">
					<div class="animate-spin rounded-full h-8 w-8 border-b-2 border-brand"></div>
				</div>
			{:else if logs.length === 0}
				<div class="text-center py-12 bg-card rounded-2xl border-2 border-dashed border-border-subtle">
					<div class="bg-surface h-16 w-16 rounded-full flex items-center justify-center mx-auto mb-4">
						<Utensils class="w-8 h-8 text-text-muted" />
					</div>
					<p class="text-text-muted font-medium mb-2">No meals logged {isToday ? 'today' : 'on this day'}</p>
					{#if isToday}
						<a href="#/log" class="text-blue-600 dark:text-blue-400 text-sm font-semibold hover:underline">Start logging now</a>
					{/if}
				</div>
			{:else}
				<div class="space-y-3">
					{#each logs as log (log.id)}
						<div class="bg-card p-4 rounded-xl shadow-sm border border-border-subtle flex justify-between items-center transition-all hover:shadow-md active:scale-[0.99] group">
							<div class="flex-1">
								<div class="flex items-center gap-2 mb-1">
									<h3 class="font-bold text-text-main group-hover:text-blue-600 dark:group-hover:text-blue-400 transition-colors">{log.food.name}</h3>
									<span class="text-[10px] font-bold uppercase tracking-wider text-text-muted bg-surface px-2 py-0.5 rounded-full">{log.meal_type}</span>
								</div>
								<p class="text-xs text-text-muted">
									{log.amount_consumed} {log.food.serving_unit || 'svg'}
								</p>
							</div>
							<div class="text-right">
								<p class="font-bold text-text-main text-lg leading-tight">{Math.round(log.food.calories * log.amount_consumed)} <span class="text-xs font-normal text-text-muted">cal</span></p>
								<div class="text-[10px] text-text-muted font-medium flex gap-1 justify-end mt-1">
									<span class="bg-purple-50 text-purple-700 dark:bg-purple-900/30 dark:text-purple-400 px-1 rounded">{Math.round(log.food.protein * log.amount_consumed)}p</span>
									<span class="bg-orange-50 text-orange-700 dark:bg-orange-900/30 dark:text-orange-400 px-1 rounded">{Math.round(log.food.carbs * log.amount_consumed)}c</span>
									<span class="bg-yellow-50 text-yellow-700 dark:bg-yellow-900/30 dark:text-yellow-400 px-1 rounded">{Math.round(log.food.fat * log.amount_consumed)}f</span>
								</div>
							</div>
						</div>
					{/each}
				</div>
			{/if}
		</div>
	</main>

	<!-- Floating Action Button -->
	<a 
		href="#/log" 
		class="fixed bottom-24 right-5 z-30 flex items-center justify-center w-14 h-14 bg-brand text-brand-fg rounded-full shadow-lg shadow-brand/30 hover:bg-brand/90 hover:scale-105 active:scale-95 transition-all focus:outline-none focus:ring-4 focus:ring-brand/30"
		aria-label="Log food"
	>
		<Plus class="w-8 h-8 stroke-[3]" />
	</a>

</div>
