// src/App.tsx
import React from 'react';
import Home from './routes/Home';
import Layout from './routes/Layout';
import { Routes, Route, BrowserRouter } from 'react-router-dom';
import Log from './routes/Log';
import FoodList from './routes/foods/Foods';
import NewFood from './routes/foods/new/NewFood';
import NewRecipe from './routes/foods/new-recipe/NewRecipe';
import AddLogEntry from './routes/log/add/AddLog';
import WorkoutList from './routes/workouts/Workouts';
import WorkoutSessionComponent from './routes/workouts/[id]/WorkoutSession';
import ExerciseSelector from './routes/workouts/exercises/ExercisesList';
import NewExercise from './routes/workouts/exercises/new/NewExercise';
import ProfileAndGoals from './routes/profile/Profile';

function App() {
return (
    <Layout>
      <Routes>
        <Route path="/log" element={<Log />} />
        <Route path="/log/add" element={<AddLogEntry />} />
        <Route path="/" element={<Home />} />
        <Route path="/foods" element={<FoodList />} />
        <Route path="/foods/new" element={<NewFood />} />
        <Route path="/foods/new-recipe" element={<NewRecipe />} />
        <Route path="/workouts" element={<WorkoutList />} />
        <Route path="/workouts/:id" element={<WorkoutSessionComponent />} />
        <Route path="/workouts/exercises" element={<ExerciseSelector />} />
        <Route path="/workouts/exercises/new" element={<NewExercise />} />
        <Route path="/profile" element={<ProfileAndGoals />} />

      </Routes>
    </Layout>
  );
}

export default App;

// src/App.svelte
<script>
  import Router from 'svelte-spa-router';
  import Layout from './routes/+layout.svelte';

  import Home from './routes/Home.svelte';
  import Workouts from './routes/Workouts.svelte';
  import Log from './routes/Log.svelte';
  import Time from './routes/Time.svelte';
  import Profile from './routes/Profile.svelte';
  import Foods from './routes/foods/Foods.svelte';
  import NewFood from './routes/foods/new/NewFood.svelte';
  import NewRecipe from './routes/foods/new-recipe/NewRecipe.svelte';
  import AddLog from './routes/log/add/AddLog.svelte';
  import Activities from './routes/time/activities/Activities.svelte';
  import AddActivityLog from './routes/time/add/AddActivityLog.svelte';
  import Exercises from './routes/workouts/exercises/Exercises.svelte';
  import NewExercise from './routes/workouts/exercises/new/NewExercise.svelte'; 
  import WorkoutDetail from './routes/workouts/[id]/Workouts.svelte';

  const routes = {
    '/': Home,
    '/workouts/exercises/new': NewExercise,
    '/workouts/exercises': Exercises,
    '/workouts/:id': WorkoutDetail,
    '/workouts': Workouts,
    '/log': Log,
    '/log/add': AddLog,
    '/time': Time,
    '/time/activities': Activities,
    '/time/add': AddActivityLog,
    '/foods': Foods,
    '/foods/new': NewFood,
    '/foods/new-recipe': NewRecipe,
    '/profile': Profile,
  };
</script>

<Layout>
  <Router {routes} useHash={true} />
</Layout>
